exclude: '.git'
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        language: python
      - id: end-of-file-fixer
        language: python
      - id: check-toml
        language: python
      - id: check-merge-conflict
        language: python
  - repo: https://github.com/psf/black
    rev: 23.1.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
